name: CI

on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2

      - name: Install JS dependencies
        run: yarn install
        
      - name: Basic JS Build
        run: npm run reactbuild
